
import React from 'react';
import { ContentType } from '@/components/stories/ContentDisplay';
import { JiraTicket } from '@/types/jira';

interface DocumentExportFormatterProps {
  content: string;
  contentType: ContentType;
  ticket: JiraTicket;
  userName?: string;
}

const DocumentExportFormatter: React.FC<DocumentExportFormatterProps> = ({
  content,
  contentType,
  ticket,
  userName = 'AI Assistant'
}) => {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const documentTitle = 
    contentType === 'lld' ? 'Low-Level Design Document' :
    contentType === 'code' ? 'Implementation Code' :
    contentType === 'tests' ? 'Unit Tests Documentation' :
    contentType === 'testcases' ? 'Test Cases Document' : 
    'Test Scripts Documentation';

  return (
    <div className="export-document prose max-w-none">
      <h1>{documentTitle}</h1>
      
      <section className="document-info">
        <h2>Document Information</h2>
        <table className="w-full border-collapse">
          <tbody>
            <tr>
              <td className="font-semibold">Document Title:</td>
              <td>{documentTitle} for {ticket.key} - {ticket.summary}</td>
            </tr>
            <tr>
              <td className="font-semibold">Version:</td>
              <td>1.0</td>
            </tr>
            <tr>
              <td className="font-semibold">Date:</td>
              <td>{date}</td>
            </tr>
            <tr>
              <td className="font-semibold">Generated By:</td>
              <td>{userName}</td>
            </tr>
            <tr>
              <td className="font-semibold">Project:</td>
              <td>{ticket.projectId || 'Unknown'}</td>
            </tr>
          </tbody>
        </table>
      </section>
      
      <section className="table-of-contents">
        <h2>Table of Contents</h2>
        <ol>
          <li>Introduction</li>
          <li>Purpose</li>
          <li>Scope</li>
          <li>Related Documents</li>
          <li>Content</li>
          <li>Revision History</li>
        </ol>
      </section>
      
      <section className="introduction">
        <h2>Introduction</h2>
        <p>This document contains {documentTitle.toLowerCase()} for the ticket: {ticket.key} - {ticket.summary}.</p>
      </section>
      
      <section className="purpose">
        <h2>Purpose</h2>
        <p>
          {contentType === 'lld' ? 
            'This document provides detailed technical specifications for implementing the required functionality.' :
            contentType === 'code' ? 
            'This document provides implementation code based on the Low-Level Design.' :
            contentType === 'tests' ? 
            'This document provides unit tests for verifying the implementation code.' :
            contentType === 'testcases' ? 
            'This document outlines comprehensive test cases for manual testing.' :
            'This document provides automated test scripts for testing the implementation.'}
        </p>
      </section>
      
      <section className="scope">
        <h2>Scope</h2>
        <p>This document covers all aspects related to the {ticket.key} ticket.</p>
      </section>
      
      <section className="related-documents">
        <h2>Related Documents</h2>
        <ul>
          <li>Jira Ticket: {ticket.key}</li>
          {contentType !== 'lld' && <li>Low-Level Design Document</li>}
          {contentType !== 'code' && contentType !== 'lld' && <li>Implementation Code Document</li>}
          {contentType === 'testScripts' && <li>Test Cases Document</li>}
        </ul>
      </section>
      
      <section className="content">
        <h2>Content</h2>
        <div className="mt-4" dangerouslySetInnerHTML={{ __html: content }} />
      </section>
      
      <section className="revision-history">
        <h2>Revision History</h2>
        <table className="w-full border-collapse">
          <thead>
            <tr>
              <th>Version</th>
              <th>Date</th>
              <th>Author</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1.0</td>
              <td>{date}</td>
              <td>{userName}</td>
              <td>Initial document generation</td>
            </tr>
          </tbody>
        </table>
      </section>
    </div>
  );
};

export default DocumentExportFormatter;
