// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gswwmieyrfdhrfwsgjnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzd3dtaWV5cmZkaHJmd3Nnam53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MjkzNjksImV4cCI6MjA2MDAwNTM2OX0.pmF7VFMO2Pu34mDWz-XnleqY0mdsePVMwltY5D4Wjvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);